### ISSUE TITLE
Simplify logic for Token generation

### ISSUE THREAD

**Issue by AMaini503** [clri/first-microservices#2]
As of now, the tenant_id is used for web token generation. I don't understand the need for using "tenant_id" in specific. 

Can we simplify that logic ? Can we just use data to generate JWT ?

**Comment by clri** [comment]
I think the tenant ID might be in place to help make sure someone isn't spoofing or stealing the token (e.g. trying to impersonate a user who is logged in on the web via a mobile app). We can always delete the tenant and add it back in later if prof/TAs say we specifically need it, though, since it's already in our commit history.
